graph TD
주차(주차) --> 주차_교과목명[교과목명]
subgraph 1단계: 클라우드 개발환경 이해 및 구축 (32일)
end
1주(1주) --> 1주_Linux[Linux]
2-3주(2-3주) --> 2-3주_MSA_개발방법[MSA 개발방법]
4-5주(4-5주) --> 4-5주_DevOps[DevOps]
6-7주(6-7주) --> 6-7주_Docker_and_Kubernetes[Docker & Kubernetes]
8주(8주) --> 8주_Git_and_보안관리[Git & 보안관리]
subgraph 2단계: 클라우드 객체지향 프로그래밍 (10일)
end
9주(9주) --> 9주_Java_기본문법[Java 기본문법]
10주(10주) --> 10주_클래스와_객체[클래스와 객체]
11주(11주) --> 11주_입출력_스트림_and_네트워크[입출력 스트림 & 네트워크]
subgraph 3단계: 클라우드 프론트엔드 개발 (15일)
end
12주(12주) --> 12주_HTML5_and_CSS3[HTML5 & CSS3]
13-14주(13-14주) --> 13-14주_Javascript[Javascript]
15주(15주) --> 15주_React[React]
subgraph 4단계: 클라우드 데이터베이스 구축 및 활용 (10일)
end
16주(16주) --> 16주_데이터베이스_구현[데이터베이스 구현]
17주(17주) --> 17주_SQL_활용_및_응용[SQL 활용 및 응용]
subgraph 5단계: 클라우드 서버 백엔드 개발 (20일)
end
18주(18주) --> 18주_JDBC[JDBC]
19-20주(19-20주) --> 19-20주_JSP_and_Servlet[JSP & Servlet]
21주(21주) --> 21주_MyBatis[MyBatis]
22주(22주) --> 22주_Spring_Boot[Spring Boot]
subgraph 6단계: 클라우드 플랫폼 기반 서비스 운영 (10일)
end
23-24주(23-24주) --> 23-24주_AWS_클라우드_웹서비스[AWS 클라우드 웹서비스]
subgraph 7단계: 실무 프로젝트 (30일)
end
25주(25주) --> 25주_MSA_기반_관광지_추천[MSA 기반 관광지 추천]
26주(26주) --> 26주_메타버스_화상회의[메타버스 화상회의]
27주(27주) --> 27주_커피전문점_관리[커피전문점 관리]
28주(28주) --> 28주_디지털교육_플랫폼[디지털교육 플랫폼]
29주(29주) --> 29주_학생역량_통합관리[학생역량 통합관리]