flowchart TD
    Start([교육시작<br/>2025.05.27]) --> Phase1{1단계: 클라우드 기반 기술<br/>05/27~06/27}

    Phase1 --> Cloud컴퓨팅[Cloud 컴퓨팅<br/>05/27~05/31<br/>개념]
    Phase1 --> Docker[Docker<br/>06/02~06/06<br/>컨테이너, 오케스트레이션]
    Phase1 --> Linux[Linux 기초<br/>06/09~06/13<br/>OS 가상화, 명령어, SSH]
    Phase1 --> Git[Git<br/>06/16~06/20<br/>형상관리, 보안관리]
    Phase1 --> DevOps[DevOps<br/>06/23~06/27<br/>CI/CD, Jenkins, Terraform]
    Phase1 --> MSA[MSA 개발방법<br/>병행 진행<br/>아키텍처, DDD, 스크럼]
    
    Docker --> Phase2{2단계: 객체지향 프로그래밍<br/>06/30~07/31<br/>Java 기반}
    
    Phase2 --> Java1[Java 기본문법<br/>06/30~07/11<br/>자료형, 제어문, 배열, 메소드]
    
    Java1 --> JavaSub1[변수와 자료형<br/>06/30~07/02<br/>기본형, 참조형, 형변환, 배열]
    Java1 --> JavaSub2[제어문<br/>07/03~07/07<br/>조건문, 반복문]
    Java1 --> JavaSub3[메소드<br/>07/08~07/11<br/>정의, 호출, 매개변수, return, 오버로딩]
    
    JavaSub1 --> Java2[클래스와 객체<br/>07/14~07/25<br/>OOP 핵심 개념]
    JavaSub2 --> Java2
    JavaSub3 --> Java2
    
    Java2 --> OOP1[캡슐화<br/>07/14~07/16<br/>정보은닉, 접근제어자]
    Java2 --> OOP2[상속<br/>07/17~07/21<br/>extends, super, 오버라이딩]
    Java2 --> OOP3[다형성<br/>07/22~07/24<br/>추상클래스, 인터페이스]
    Java2 --> OOP4[고급 개념<br/>07/25<br/>제네릭, 컬렉션, 예외처리]
    
    OOP1 --> Java3[입출력 & 네트워크<br/>07/28~07/31<br/>실무 프로그래밍]
    OOP2 --> Java3
    OOP3 --> Java3
    OOP4 --> Java3
    
    Java3 --> IO1[입출력 스트림<br/>07/28~07/29<br/>InputStream/OutputStream]
    Java3 --> IO2[파일 처리<br/>07/30~07/31<br/>File 클래스, 직렬화]
    
    IO2 --> Phase3{3단계: 웹 기초 기술<br/>08/01~08/29}
    
    Phase3 --> HTML[HTML5<br/>08/01~08/08<br/>시맨틱 태그, 폼 요소]
    Phase3 --> CSS[CSS3<br/>08/11~08/15<br/>스타일링, 레이아웃]
    
    HTML --> HTMLSub1[기본 구조<br/>08/01~08/04<br/>태그, 속성, 문서 구조화]
    HTML --> HTMLSub2[폼과 입력<br/>08/05~08/08<br/>form, input, validation]
    
    CSS --> CSSSub1[선택자와 속성<br/>08/11~08/12<br/>박스 모델, 포지셔닝]
    CSS --> CSSSub2[Flexbox<br/>08/13~08/15<br/>Grid Layout]
    
    HTMLSub2 --> JS[Javascript 기초<br/>08/18~08/29<br/>DOM 조작, 이벤트]
    CSSSub2 --> JS
    
    JS --> JSSub1[기본 문법<br/>08/18~08/20<br/>변수, 함수, 객체, 배열]
    JS --> JSSub2[DOM 조작<br/>08/21~08/22<br/>요소 선택, 스타일 변경]
    JS --> JSSub3[이벤트 처리<br/>08/25~08/27<br/>클릭, 키보드, 폼 이벤트]
    JS --> JSSub4[비동기 처리<br/>08/28~08/29<br/>Promise, async/await, fetch API]
    
    JSSub4 --> Phase4{4단계: 데이터베이스<br/>09/01~09/30<br/>심화 학습}
    
    Phase4 --> DB1[DB 구현 & 모델링<br/>09/01~09/15<br/>DBMS 기초, 설계]
    Phase4 --> DB2[SQL 활용<br/>09/16~09/30<br/>기본/고급 SQL]
    
    DB1 --> DBSub1[DBMS 개요<br/>09/01~09/03<br/>관계형 DB 개념, 설치]
    DB1 --> DBSub2[데이터 모델링<br/>09/04~09/08<br/>개념적, 논리적, 물리적]
    DB1 --> DBSub3[ERD 설계<br/>09/09~09/12<br/>엔터티, 관계, 속성]
    DB1 --> DBSub4[정규화<br/>09/13~09/15<br/>1NF, 2NF, 3NF, 반정규화]
    
    DBSub1 --> DBMiddle[데이터 무결성<br/>09/16<br/>제약조건 설계, PK, FK]
    DBSub2 --> DBMiddle
    DBSub3 --> DBMiddle
    DBSub4 --> DBMiddle
    
    DBMiddle --> DB2
    
    DB2 --> SQLSub1[기본 SQL<br/>09/17~09/22<br/>DDL, DML, DCL]
    DB2 --> SQLSub2[고급 SQL<br/>09/23~09/30<br/>JOIN, SubQuery, 집계함수]
    
    SQLSub1 --> SQLPractice[실습 프로젝트<br/>09/29~09/30<br/>쇼핑몰 DB 설계]
    SQLSub2 --> SQLPractice
    
    SQLPractice --> Phase5{5단계: 백엔드 개발<br/>10/01~10/31<br/>웹 서버 구축}
    
    Phase5 --> JDBC[JDBC<br/>10/01~10/08<br/>Java DB 연동]
    Phase5 --> WebDev[웹 개발 기초<br/>10/09~10/20<br/>JSP & Servlet]
    Phase5 --> Framework[프레임워크<br/>10/21~10/31<br/>MyBatis & Spring]
    
    JDBC --> JDBCSub1[JDBC 드라이버<br/>10/01~10/02<br/>Connection 객체]
    JDBC --> JDBCSub2[Statement vs PreparedStatement<br/>10/03~10/05<br/>SQL Injection 방지]
    JDBC --> JDBCSub3[Connection Pool<br/>10/06~10/07<br/>DBCP, HikariCP]
    JDBC --> JDBCSub4[트랜잭션 관리<br/>10/08<br/>commit, rollback]
    
    JDBCSub1 --> WebDev
    JDBCSub2 --> WebDev
    JDBCSub3 --> WebDev
    JDBCSub4 --> WebDev
    
    WebDev --> JSPSub1[JSP 기초<br/>10/09~10/13<br/>디렉티브, 스크립트릿]
    WebDev --> JSPSub2[JSP 고급<br/>10/14~10/16<br/>액션 태그, JSTL, EL]
    WebDev --> ServletSub1[Servlet 기초<br/>10/17~10/20<br/>라이프사이클]
    
    JSPSub1 --> MVCPattern[MVC 패턴<br/>10/21~10/22<br/>Model2 구조]
    JSPSub2 --> MVCPattern
    ServletSub1 --> MVCPattern
    
    MVCPattern --> WebProject[웹 프로젝트<br/>10/23~10/24<br/>게시판 구현]
    
    WebProject --> Framework
    
    Framework --> MyBatisPart[MyBatis<br/>10/25~10/27<br/>SQL 매퍼 프레임워크]
    Framework --> SpringPart[Spring Boot<br/>10/28~10/31<br/>엔터프라이즈 프레임워크]
    
    MyBatisPart --> MyBSub1[MyBatis 설정<br/>10/25<br/>configuration.xml, mapper.xml]
    MyBatisPart --> MyBSub2[동적 SQL<br/>10/26<br/>if, choose, foreach]
    MyBatisPart --> MyBSub3[DAO 패턴<br/>10/27<br/>SqlSession, Mapper]
    
    MyBSub3 --> SpringPart
    
    SpringPart --> SpringSub1[Spring 핵심<br/>10/28<br/>IoC Container, DI]
    SpringPart --> SpringSub2[Spring AOP<br/>10/29<br/>관점지향 프로그래밍]
    SpringPart --> SpringSub3[Spring MVC<br/>10/30<br/>DispatcherServlet]
    SpringPart --> SpringSub4[Spring Boot<br/>10/31<br/>자동 설정, 스타터]
    
    SpringSub4 --> Phase6{6단계: 모던 프론트엔드<br/>11/01~11/29<br/>React 기반}
    
    Phase6 --> Node[Node.js 환경<br/>11/01~11/05<br/>npm, yarn, 패키지 관리]
    Phase6 --> ReactBasic[React 기초<br/>11/06~11/15<br/>컴포넌트, JSX]
    Phase6 --> ReactAdvanced[React 심화<br/>11/16~11/29<br/>상태관리, 라우팅]
    
    Node --> NodeSub1[패키지 관리<br/>11/01~11/03<br/>npm install, package.json]
    Node --> NodeSub2[개발 환경<br/>11/04~11/05<br/>create-react-app, webpack]
    
    ReactBasic --> ReactSub1[컴포넌트<br/>11/06~11/08<br/>함수형, 클래스형, props]
    ReactBasic --> ReactSub2[JSX 문법<br/>11/11~11/12<br/>조건부 렌더링, 리스트]
    ReactBasic --> ReactSub3[이벤트 처리<br/>11/13~11/15<br/>폼 처리, 생명주기]
    
    ReactAdvanced --> ReactSub4[Hooks<br/>11/16~11/20<br/>useState, useEffect]
    ReactAdvanced --> ReactSub5[상태 관리<br/>11/21~11/25<br/>Context API, Redux]
    ReactAdvanced --> ReactSub6[라우팅<br/>11/26~11/29<br/>React Router]
    
    %% 7단계 클라우드 플랫폼 병행
    DevOps --> CloudPhase7[7단계: 클라우드 플랫폼 병행<br/>06/23~08/29<br/>AWS 실습]
    JS --> CloudPhase7
    CloudPhase7 --> AWSBasic[AWS 기초<br/>06/23~07/15<br/>EC2, S3]
    CloudPhase7 --> AWSAdvanced[AWS 고급<br/>08/01~08/29<br/>RDS, Lambda]
    
    %% 8단계 실무 프로젝트 병행
    SQLPractice --> ProjectPhase8[8단계: 실무 프로젝트 병행<br/>09/29~11/29<br/>점진적 완성]
    SpringSub4 --> ProjectPhase8
    ReactSub6 --> ProjectPhase8
    AWSAdvanced --> ProjectPhase8
    
    ProjectPhase8 --> Proj1[관광지 추천 서비스<br/>10/01~10/15<br/>DB + 백엔드 API]
    ProjectPhase8 --> Proj2[메타버스 화상회의<br/>10/16~10/31<br/>Spring Boot + WebRTC]
    ProjectPhase8 --> Proj3[커피전문점 관리<br/>11/01~11/15<br/>React + Spring Boot]
    ProjectPhase8 --> Proj4[디지털교육 플랫폼<br/>11/16~11/25<br/>풀스택 + AWS]
    ProjectPhase8 --> Proj5[학생역량 통합관리<br/>11/26~11/29<br/>최종 통합]
    
    ReactSub6 --> Complete([교육완료<br/>2025.11.29<br/>클라우드 데브옵스 전문가])
    Proj5 --> Complete
    
    classDef phase1 fill:#e8f5e8
    classDef phase2 fill:#fff2e8
    classDef phase3 fill:#e8f0ff
    classDef phase4 fill:#f0e8ff
    classDef phase5 fill:#ffe8f0
    classDef phase6 fill:#ffeaa7
    classDef phase7 fill:#f8f8e8
    classDef phase8 fill:#ffebcd
    classDef milestone fill:#ff6b6b,color:#fff
    
    class Linux,MSA,DevOps,Docker,Git,Cloud컴퓨팅 phase1
    class Java1,Java2,Java3,JavaSub1,JavaSub2,JavaSub3,OOP1,OOP2,OOP3,OOP4,IO1,IO2 phase2
    class HTML,CSS,HTMLSub1,HTMLSub2,CSSSub1,CSSSub2,JS,JSSub1,JSSub2,JSSub3,JSSub4 phase3
    class DB1,DB2,DBSub1,DBSub2,DBSub3,DBSub4,DBMiddle,SQLSub1,SQLSub2,SQLPractice phase4
    class JDBC,WebDev,Framework,JDBCSub1,JDBCSub2,JDBCSub3,JDBCSub4,JSPSub1,JSPSub2,ServletSub1,MVCPattern,WebProject,MyBatisPart,SpringPart,MyBSub1,MyBSub2,MyBSub3,SpringSub1,SpringSub2,SpringSub3,SpringSub4 phase5
    class Node,ReactBasic,ReactAdvanced,NodeSub1,NodeSub2,ReactSub1,ReactSub2,ReactSub3,ReactSub4,ReactSub5,ReactSub6 phase6
    class CloudPhase7,AWSBasic,AWSAdvanced phase7
    class ProjectPhase8,Proj1,Proj2,Proj3,Proj4,Proj5 phase8
    class Start,Complete milestone